# Generated by Django 2.1 on 2019-06-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermisPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gn_is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='gn_is_staff',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='gn_is_superuser',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='kb_is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='kb_is_staff',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='kb_is_superuser',
            field=models.BooleanField(),
        ),
    ]
