# Generated by Django 2.1 on 2019-09-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermisPortal', '0005_auto_20190628_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kb_is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
