"""
Django settings for ermisAuth project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from django.utils.translation import ugettext_lazy as _
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*o3!)h5dyex6_0p05w3cua^$=_4t9)x@kma0^=$0%7v)5h2qch'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['84.205.200.64','10.128.86.242','service.ermis-f.eu']


# Application definition

INSTALLED_APPS = [
    'ermisPortal',
    #added start
    'captcha',
    'dl_user',
    'anymail',
    'crispy_forms',
    'bootstrap3',
    'mama_cas',
    #added end
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ermisAuth.urls'

#added start
import ldap,ermisAuth
from django_auth_ldap.config import LDAPSearch,LDAPSearchUnion,GroupOfNamesType, PosixGroupType,NestedGroupOfNamesType

AUTH_USER_MODEL = 'ermisPortal.User'
AUTHENTICATION_BACKENDS = [
#'ermisAuth.auth_backends.ErmisUserModelBackend',
'django_auth_ldap.backend.LDAPBackend',
'django.contrib.auth.backends.ModelBackend',
]
AUTH_LDAP_SERVER_URI = 'ldap://127.0.0.1'
LDAP_SEARCH_DN = 'cn=users,dc=ermis-f,dc=eu'
AUTH_LDAP_USER = '(uid=%(user)s)'
AUTH_LDAP_BIND_DN = 'cn=admin,dc=ermis-f,dc=eu'
AUTH_LDAP_BIND_PASSWORD = 'Erm_F2018'
#AUTH_LDAP_BIND_DN = ""
#AUTH_LDAP_BIND_PASSWORD = ""
AUTH_LDAP_USER_ATTR_MAP = {
        'first_name': 'givenName','last_name':'sn','email':'mail','organization':'description'
}
AUTH_LDAP_USER_SEARCH = LDAPSearch(LDAP_SEARCH_DN,ldap.SCOPE_SUBTREE, AUTH_LDAP_USER)
#AUTH_LDAP_USER_SEARCH =LDAPSearchUnion( 
#  LDAPSearch(LDAP_SEARCH_DN,ldap.SCOPE_SUBTREE, AUTH_LDAP_USER),
#  LDAPSearch(LDAP_SEARCH_DN,ldap.SCOPE_SUBTREE, '(mail=%(user)s)'),
#  )


AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
'ou=groups,dc=ermis-f,dc=eu',
ldap.SCOPE_SUBTREE,
'(objectClass=groupOfNames)',
)
AUTH_LDAP_GROUP_TYPE = NestedGroupOfNamesType()
#AUTH_LDAP_REQUIRE_GROUP = "ou=geonode,dc=ermis-floods-dev,dc=aegean,dc=gr"

AUTH_LDAP_FIND_GROUP_PERMS=True
AUTH_LDAP_MIRROR_GROUPS=True
AUTH_LDAP_ALWAYS_UPDATE_USER=True
AUTH_LDAP_AUTHORIZE_ALL_USERS=True
#if mama_cas.SERVICE_PROVIDER_URL == 'http://geoportal.ermis-f.eu':
AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
'ou=groups,dc=ermis-f,dc=eu',
ldap.SCOPE_SUBTREE,
'(objectClass=groupOfNames)',
)
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
"gn_is_active": "cn=active,ou=gn,ou=groups,dc=ermis-f,dc=eu",
"gn_is_staff": "cn=staff,ou=gn,ou=groups,dc=ermis-f,dc=eu",
"gn_is_superuser": "cn=superuser,ou=gn,ou=groups,dc=ermis-f,dc=eu",
"kb_is_active": "cn=active,ou=kb,ou=groups,dc=ermis-f,dc=eu",
"kb_is_staff": "cn=staff,ou=kb,ou=groups,dc=ermis-f,dc=eu",
"kb_is_superuser": "cn=superuser,ou=kb,ou=groups,dc=ermis-f,dc=eu",
"kb_is_editor": "cn=kb_editor,ou=kb,ou=groups,dc=ermis-f,dc=eu",
"cr_is_active": "cn=active,ou=cr,ou=groups,dc=ermis-f,dc=eu",
"cr_is_staff": "cn=staff,ou=cr,ou=groups,dc=ermis-f,dc=eu",
"cr_is_superuser": "cn=superuser,ou=cr,ou=groups,dc=ermis-f,dc=eu",
"cr_is_editor": "cn=cr_editor,ou=cr,ou=groups,dc=ermis-f,dc=eu",
"sm_is_active": "cn=active,ou=sm,ou=groups,dc=ermis-f,dc=eu",
"sm_is_staff": "cn=staff,ou=sm,ou=groups,dc=ermis-f,dc=eu",
"sm_is_superuser": "cn=superuser,ou=sm,ou=groups,dc=ermis-f,dc=eu",
"ews_is_active": "cn=active,ou=ews,ou=groups,dc=ermis-f,dc=eu",
"ews_is_staff": "cn=staff,ou=ews,ou=groups,dc=ermis-f,dc=eu",
"ews_is_superuser": "cn=superuser,ou=ews,ou=groups,dc=ermis-f,dc=eu",
"is_active": "cn=active,ou=sso,ou=groups,dc=ermis-f,dc=eu",
"is_staff": "cn=staff,ou=sso,ou=groups,dc=ermis-f,dc=eu",
"is_superuser": "cn=superuser,ou=sso,ou=groups,dc=ermis-f,dc=eu",
}

AUTH_LDAP_CONNECTION_OPTIONS = {
ldap.OPT_DEBUG_LEVEL: 3,
ldap.OPT_REFERRALS: 0,
}
#ldap registration settings
# Site
SITE_BASE_URL = 'https://service.ermis-f.eu' # No trailing slash
#MAMA_CAS_ATTRIBUTE_CALLBACKS = ('path.to.custom_attributes',)
#def custom_attributes(user, service):
#    return {'givenName': user.first_name, 'email': 'test@aaa.gr', 'short_name': user.short_name}
MAMA_CAS_SERVICES = [
    {
        'SERVICE': 'https://geoportal.ermis-f.eu',
        'CALLBACKS': ['ermisPortal.callbacks.geoServiceAttribs',],
        'LOGOUT_ALLOW': True,
        'LOGOUT_URL': 'https://geoportal.ermis-f.eu/account/logout',
    },
    {
        'SERVICE': 'https://cr.ermis-f.eu',
        'CALLBACKS': ['ermisPortal.callbacks.geoServiceAttribs',],
        'LOGOUT_ALLOW': True,
        'LOGOUT_URL': 'https://cr.ermis-f.eu/account/logout',
    },
    {
        'SERVICE': 'https://kb.ermis-f.eu',
        'CALLBACKS': ['ermisPortal.callbacks.geoServiceAttribs',],
        'LOGOUT_ALLOW': True,
        'LOGOUT_URL': 'https://kb.ermis-f.eu/account/logout',
    },
    {
        'SERVICE': 'https://sm.ermis-f.eu',
        'CALLBACKS': ['ermisPortal.callbacks.geoServiceAttribs',],
        'LOGOUT_ALLOW': True,
        'LOGOUT_URL': 'https://sm.ermis-f.eu/account/logout/',
    },
    {
        'SERVICE': 'https://ews.ermis-f.eu',
        'CALLBACKS': ['ermisPortal.callbacks.geoServiceAttribs',],
        'LOGOUT_ALLOW': True,
        'LOGOUT_URL': 'https://ews.ermis-f.eu/account/logout/',
    },
       {
        'SERVICE': 'https://ermis-f.eu',
        'CALLBACKS': ['ermisPortal.callbacks.geoServiceAttribs',],
        'LOGOUT_ALLOW': True,
        'LOGOUT_URL': 'https://ermis-f.eu/account/logout/',
    },

 ]

SESSION_COOKIE_AGE = 36000
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#TIME_ZONE = 'Africa/Nairobi'
# IDP Details
IDP_NAME = 'ERMIS-F Service'
IDP_LOGO = 'https://ermis-f.eu/wp-content/uploads/2018/06/Ermisxlnew2-672x368.png' # Width of 200px at least
# Test service provider
#SERVICE_PROVIDER = 'Test service provider'
#SERVICE_PROVIDER_URL = 'https://test-service.kenet.or.ke'
# This setting enables capturing of a users institution and country details
IDP_CATCH_ALL = True
# LDAP Settings
LDAP_PROTO = 'ldap'
LDAP_HOST = '127.0.0.1'
LDAP_PORT = '389' # must be str
LDAP_BASE_DN = 'cn=users,dc=ermis-f,dc=eu'
LDAP_BIND_DN = 'cn=admin,dc=ermis-f,dc=eu'
LDAP_BIND_DN_CREDENTIAL = 'Erm_F2018'
LDAP_GID = "501" # group ID to add signed up users
LDAP_BASE_UID = 1000 # Integer

# Password Reset

PASSWORD_RESET_TOKEN_EXPIRY = 2 #Hours

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'ermisfservice@gmail.com'
EMAIL_HOST_PASSWORD = 'Erm_F2018'
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 100

#EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
#ANYMAIL = {
#"MAILGUN_API_KEY": "<your key>",
#}

DEFAULT_FROM_EMAIL = IDP_NAME + ' <ermisfservice@gmail.com>'

CRISPY_TEMPLATE_PACK = 'bootstrap3'
LDAP_USER_DATA = ['Organization'  ]
TESTING = True
RECAPTCHA_PUBLIC_KEY = '6Ld_dagUAAAAACtxLb0JPrq9FUpIkFnWEPlwfMkY'
RECAPTCHA_PRIVATE_KEY = '6Ld_dagUAAAAAI3GFOESU8w6tQeWDvjMh1j-7RGR'
BOOTSTRAP3 = { "theme_url": "https://bootswatch.com/3/flatly/bootstrap.min.css",   }
#added end

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates') ] ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ermisAuth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ermisCAS',
        'USER': 'ermisCASuser',
        'PASSWORD': 'ekZ6Cd1e_Cvrm5Xl8',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
#def custom_attributes(user, service):
#    return {'givenName': user.first_name, 'email': user.email}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGES = (
    ('en', _('English')),
    ('el', _('Greek')),
)

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.join('/home/geo/ermisAuth', 'locale'),
    os.path.join("/home/geo/py3env/lib/python3.6/site-packages/mama_cas/", "locale"),
    os.path.join("/home/geo/py3env/lib/python3.6/site-packages/dl_user/","locale"),
)



MAMA_CAS_ENABLE_SINGLE_SIGN_OUT = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
